[2024-11-12T01:45:46.585+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T01:45:46.687+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.extract_stock_data manual__2024-11-12T01:45:36.433027+00:00 [queued]>
[2024-11-12T01:45:46.714+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.extract_stock_data manual__2024-11-12T01:45:36.433027+00:00 [queued]>
[2024-11-12T01:45:46.716+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T01:45:46.755+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_stock_data> on 2024-11-12 01:45:36.433027+00:00
[2024-11-12T01:45:46.789+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6498) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T01:45:46.793+0000] {standard_task_runner.py:63} INFO - Started process 6510 to run task
[2024-11-12T01:45:46.793+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'StockForcastingNext7WorkingDaysTodayOnward', 'extract_stock_data', 'manual__2024-11-12T01:45:36.433027+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/Conn_Forcasting_DagFile.py', '--cfg-path', '/tmp/tmpjrrxs05l']
[2024-11-12T01:45:46.823+0000] {standard_task_runner.py:91} INFO - Job 92: Subtask extract_stock_data
[2024-11-12T01:45:47.126+0000] {task_command.py:426} INFO - Running <TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.extract_stock_data manual__2024-11-12T01:45:36.433027+00:00 [running]> on host d99256b0cb87
[2024-11-12T01:45:47.401+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='StockForcastingNext7WorkingDaysTodayOnward' AIRFLOW_CTX_TASK_ID='extract_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T01:45:36.433027+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T01:45:36.433027+00:00'
[2024-11-12T01:45:47.406+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T01:45:47.446+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T01:45:47.449+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Conn_Forcasting_DagFile.py", line 19, in extract_stock_data
    API_KEY = Variable.get("api_key")
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_key does not exist'
[2024-11-12T01:45:47.578+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=StockForcastingNext7WorkingDaysTodayOnward, task_id=extract_stock_data, run_id=manual__2024-11-12T01:45:36.433027+00:00, execution_date=20241112T014536, start_date=20241112T014546, end_date=20241112T014547
[2024-11-12T01:45:47.737+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 92 for task extract_stock_data ('Variable api_key does not exist'; 6510)
[2024-11-12T01:45:47.847+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T01:45:48.143+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T01:45:48.188+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
