[2024-11-12T02:01:19.039+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T02:01:19.305+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.load90DaysDataToSnowflake manual__2024-11-12T02:00:53.215720+00:00 [queued]>
[2024-11-12T02:01:19.372+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.load90DaysDataToSnowflake manual__2024-11-12T02:00:53.215720+00:00 [queued]>
[2024-11-12T02:01:19.375+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T02:01:19.462+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load90DaysDataToSnowflake> on 2024-11-12 02:00:53.215720+00:00
[2024-11-12T02:01:19.563+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'StockForcastingNext7WorkingDaysTodayOnward', 'load90DaysDataToSnowflake', 'manual__2024-11-12T02:00:53.215720+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/Conn_Forcasting_DagFile.py', '--cfg-path', '/tmp/tmpfgdhvjrt']
[2024-11-12T02:01:19.581+0000] {standard_task_runner.py:91} INFO - Job 110: Subtask load90DaysDataToSnowflake
[2024-11-12T02:01:19.594+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7303) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T02:01:19.645+0000] {standard_task_runner.py:63} INFO - Started process 7327 to run task
[2024-11-12T02:01:21.161+0000] {task_command.py:426} INFO - Running <TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.load90DaysDataToSnowflake manual__2024-11-12T02:00:53.215720+00:00 [running]> on host d99256b0cb87
[2024-11-12T02:01:22.716+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='StockForcastingNext7WorkingDaysTodayOnward' AIRFLOW_CTX_TASK_ID='load90DaysDataToSnowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T02:00:53.215720+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T02:00:53.215720+00:00'
[2024-11-12T02:01:22.721+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T02:01:22.778+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T02:01:22.955+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Conn_Forcasting_DagFile.py", line 42, in load90DaysDataToSnowflake
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Conn_Forcasting_DagFile.py", line 14, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 286, in get_conn
    conn_config = self._get_conn_params()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 185, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_Forcasting` isn't defined
[2024-11-12T02:01:23.013+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=StockForcastingNext7WorkingDaysTodayOnward, task_id=load90DaysDataToSnowflake, run_id=manual__2024-11-12T02:00:53.215720+00:00, execution_date=20241112T020053, start_date=20241112T020119, end_date=20241112T020123
[2024-11-12T02:01:23.127+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 110 for task load90DaysDataToSnowflake (The conn_id `snowflake_Forcasting` isn't defined; 7327)
[2024-11-12T02:01:23.197+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T02:01:23.266+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T02:01:23.270+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
