[2024-11-12T01:51:13.294+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T01:51:13.397+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.extract_stock_data manual__2024-11-12T01:51:02.187158+00:00 [queued]>
[2024-11-12T01:51:13.424+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.extract_stock_data manual__2024-11-12T01:51:02.187158+00:00 [queued]>
[2024-11-12T01:51:13.425+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T01:51:13.466+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_stock_data> on 2024-11-12 01:51:02.187158+00:00
[2024-11-12T01:51:13.498+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6749) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T01:51:13.497+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'StockForcastingNext7WorkingDaysTodayOnward', 'extract_stock_data', 'manual__2024-11-12T01:51:02.187158+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/Conn_Forcasting_DagFile.py', '--cfg-path', '/tmp/tmpgwa7asd4']
[2024-11-12T01:51:13.503+0000] {standard_task_runner.py:63} INFO - Started process 6767 to run task
[2024-11-12T01:51:13.503+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask extract_stock_data
[2024-11-12T01:51:13.714+0000] {task_command.py:426} INFO - Running <TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.extract_stock_data manual__2024-11-12T01:51:02.187158+00:00 [running]> on host d99256b0cb87
[2024-11-12T01:51:14.019+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='StockForcastingNext7WorkingDaysTodayOnward' AIRFLOW_CTX_TASK_ID='extract_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T01:51:02.187158+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T01:51:02.187158+00:00'
[2024-11-12T01:51:14.027+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T01:51:14.680+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T01:51:14.682+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Conn_Forcasting_DagFile.py", line 23, in extract_stock_data
    data = response.json()["Time Series (Daily)"]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Time Series (Daily)'
[2024-11-12T01:51:14.809+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=StockForcastingNext7WorkingDaysTodayOnward, task_id=extract_stock_data, run_id=manual__2024-11-12T01:51:02.187158+00:00, execution_date=20241112T015102, start_date=20241112T015113, end_date=20241112T015114
[2024-11-12T01:51:14.931+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 95 for task extract_stock_data ('Time Series (Daily)'; 6767)
[2024-11-12T01:51:15.075+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T01:51:15.284+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T01:51:15.305+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
