[2024-11-12T01:29:05.616+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T01:29:05.723+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.extract_stock_data__1 manual__2024-11-12T01:28:53.265494+00:00 [queued]>
[2024-11-12T01:29:05.776+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.extract_stock_data__1 manual__2024-11-12T01:28:53.265494+00:00 [queued]>
[2024-11-12T01:29:05.779+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T01:29:05.848+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_stock_data__1> on 2024-11-12 01:28:53.265494+00:00
[2024-11-12T01:29:05.901+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'StockForcastingNext7WorkingDaysTodayOnward', 'extract_stock_data__1', 'manual__2024-11-12T01:28:53.265494+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/Conn_Forcasting_DagFile.py', '--cfg-path', '/tmp/tmp0scow4v5']
[2024-11-12T01:29:05.937+0000] {standard_task_runner.py:91} INFO - Job 82: Subtask extract_stock_data__1
[2024-11-12T01:29:05.997+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5674) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T01:29:06.014+0000] {standard_task_runner.py:63} INFO - Started process 5692 to run task
[2024-11-12T01:29:06.407+0000] {task_command.py:426} INFO - Running <TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.extract_stock_data__1 manual__2024-11-12T01:28:53.265494+00:00 [running]> on host d99256b0cb87
[2024-11-12T01:29:07.712+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='StockForcastingNext7WorkingDaysTodayOnward' AIRFLOW_CTX_TASK_ID='extract_stock_data__1' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T01:28:53.265494+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T01:28:53.265494+00:00'
[2024-11-12T01:29:07.733+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T01:29:07.830+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T01:29:07.835+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Conn_Forcasting_DagFile.py", line 19, in extract_stock_data
    API_KEY = Variable.get("api_key")
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_key does not exist'
[2024-11-12T01:29:07.980+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=StockForcastingNext7WorkingDaysTodayOnward, task_id=extract_stock_data__1, run_id=manual__2024-11-12T01:28:53.265494+00:00, execution_date=20241112T012853, start_date=20241112T012905, end_date=20241112T012907
[2024-11-12T01:29:08.114+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 82 for task extract_stock_data__1 ('Variable api_key does not exist'; 5692)
[2024-11-12T01:29:08.176+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T01:29:08.229+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
