[2024-11-15T06:11:42.499+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-15T06:11:42.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: YfinanceToSnowflake.dbt_test manual__2024-11-15T05:56:05.666841+00:00 [queued]>
[2024-11-15T06:11:42.649+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: YfinanceToSnowflake.dbt_test manual__2024-11-15T05:56:05.666841+00:00 [queued]>
[2024-11-15T06:11:42.650+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-11-15T06:11:42.687+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-11-15 05:56:05.666841+00:00
[2024-11-15T06:11:42.706+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=21589) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-15T06:11:42.708+0000] {standard_task_runner.py:63} INFO - Started process 21606 to run task
[2024-11-15T06:11:42.705+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'YfinanceToSnowflake', 'dbt_test', 'manual__2024-11-15T05:56:05.666841+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/Conn_Forcasting_DagFile.py', '--cfg-path', '/tmp/tmpddxkosp6']
[2024-11-15T06:11:42.711+0000] {standard_task_runner.py:91} INFO - Job 392: Subtask dbt_test
[2024-11-15T06:11:42.895+0000] {task_command.py:426} INFO - Running <TaskInstance: YfinanceToSnowflake.dbt_test manual__2024-11-15T05:56:05.666841+00:00 [running]> on host 5bbe89177473
[2024-11-15T06:11:43.490+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='YfinanceToSnowflake' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T05:56:05.666841+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T05:56:05.666841+00:00'
[2024-11-15T06:11:43.492+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-15T06:11:43.494+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-15T06:11:43.498+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/stocks_mau && dbt test --profiles-dir /opt/***/stocks_mau']
[2024-11-15T06:11:43.531+0000] {subprocess.py:86} INFO - Output:
[2024-11-15T06:11:56.736+0000] {subprocess.py:93} INFO - [0m06:11:56  Running with dbt=1.8.7
[2024-11-15T06:12:08.940+0000] {subprocess.py:93} INFO - [0m06:12:08  Registered adapter: snowflake=1.8.4
[2024-11-15T06:12:16.574+0000] {subprocess.py:93} INFO - [0m06:12:16  Found 2 snapshots, 2 models, 6 data tests, 1 source, 459 macros
[2024-11-15T06:12:16.583+0000] {subprocess.py:93} INFO - [0m06:12:16
[2024-11-15T06:12:17.463+0000] {subprocess.py:93} INFO - [0m06:12:17  Concurrency: 1 threads (target='dev')
[2024-11-15T06:12:17.468+0000] {subprocess.py:93} INFO - [0m06:12:17
[2024-11-15T06:12:17.525+0000] {subprocess.py:93} INFO - [0m06:12:17  1 of 6 START test not_null_moving_average_date ................................. [RUN]
[2024-11-15T06:12:18.338+0000] {subprocess.py:93} INFO - [0m06:12:18  1 of 6 PASS not_null_moving_average_date ....................................... [[32mPASS[0m in 0.81s]
[2024-11-15T06:12:18.344+0000] {subprocess.py:93} INFO - [0m06:12:18  2 of 6 START test not_null_moving_average_symbol ............................... [RUN]
[2024-11-15T06:12:19.151+0000] {subprocess.py:93} INFO - [0m06:12:19  2 of 6 PASS not_null_moving_average_symbol ..................................... [[32mPASS[0m in 0.80s]
[2024-11-15T06:12:19.168+0000] {subprocess.py:93} INFO - [0m06:12:19  3 of 6 START test not_null_rsi_date ............................................ [RUN]
[2024-11-15T06:12:20.334+0000] {subprocess.py:93} INFO - [0m06:12:20  3 of 6 PASS not_null_rsi_date .................................................. [[32mPASS[0m in 1.14s]
[2024-11-15T06:12:20.378+0000] {subprocess.py:93} INFO - [0m06:12:20  4 of 6 START test not_null_rsi_symbol .......................................... [RUN]
[2024-11-15T06:12:21.837+0000] {subprocess.py:93} INFO - [0m06:12:21  4 of 6 PASS not_null_rsi_symbol ................................................ [[32mPASS[0m in 1.44s]
[2024-11-15T06:12:21.850+0000] {subprocess.py:93} INFO - [0m06:12:21  5 of 6 START test unique_moving_average_date__symbol ........................... [RUN]
[2024-11-15T06:12:21.944+0000] {subprocess.py:93} INFO - [0m06:12:21  5 of 6 ERROR unique_moving_average_date__symbol ................................ [[31mERROR[0m in 0.09s]
[2024-11-15T06:12:21.954+0000] {subprocess.py:93} INFO - [0m06:12:21  6 of 6 START test unique_rsi_date__symbol ...................................... [RUN]
[2024-11-15T06:12:21.978+0000] {subprocess.py:93} INFO - [0m06:12:21  6 of 6 ERROR unique_rsi_date__symbol ........................................... [[31mERROR[0m in 0.02s]
[2024-11-15T06:12:21.993+0000] {subprocess.py:93} INFO - [0m06:12:21
[2024-11-15T06:12:21.995+0000] {subprocess.py:93} INFO - [0m06:12:21  Finished running 6 data tests in 0 hours 0 minutes and 5.41 seconds (5.41s).
[2024-11-15T06:12:22.727+0000] {subprocess.py:93} INFO - [0m06:12:22
[2024-11-15T06:12:22.731+0000] {subprocess.py:93} INFO - [0m06:12:22  [31mCompleted with 2 errors and 0 warnings:[0m
[2024-11-15T06:12:22.982+0000] {subprocess.py:93} INFO - [0m06:12:22
[2024-11-15T06:12:23.011+0000] {subprocess.py:93} INFO - [0m06:12:23    Compilation Error in test unique_moving_average_date__symbol (models/input/schema.yml)
[2024-11-15T06:12:23.018+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__test_unique' takes no keyword argument 'combination_of_columns'
[2024-11-15T06:12:23.029+0000] {subprocess.py:93} INFO - [0m06:12:23
[2024-11-15T06:12:23.041+0000] {subprocess.py:93} INFO - [0m06:12:23    Compilation Error in test unique_rsi_date__symbol (models/input/schema.yml)
[2024-11-15T06:12:23.062+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__test_unique' takes no keyword argument 'combination_of_columns'
[2024-11-15T06:12:23.068+0000] {subprocess.py:93} INFO - [0m06:12:23
[2024-11-15T06:12:23.103+0000] {subprocess.py:93} INFO - [0m06:12:23  Done. PASS=4 WARN=0 ERROR=2 SKIP=0 TOTAL=6
[2024-11-15T06:12:26.316+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-15T06:12:26.319+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-15T06:12:26.409+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-15T06:12:26.430+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=YfinanceToSnowflake, task_id=dbt_test, run_id=manual__2024-11-15T05:56:05.666841+00:00, execution_date=20241115T055605, start_date=20241115T061142, end_date=20241115T061226
[2024-11-15T06:12:26.564+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 392 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 21606)
[2024-11-15T06:12:26.726+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-15T06:12:26.915+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T06:12:26.934+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
