[2024-11-15T06:14:18.453+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-15T06:14:18.562+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: YfinanceToSnowflake.dbt_test manual__2024-11-15T05:56:05.666841+00:00 [queued]>
[2024-11-15T06:14:18.603+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: YfinanceToSnowflake.dbt_test manual__2024-11-15T05:56:05.666841+00:00 [queued]>
[2024-11-15T06:14:18.605+0000] {taskinstance.py:2306} INFO - Starting attempt 7 of 7
[2024-11-15T06:14:18.672+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-11-15 05:56:05.666841+00:00
[2024-11-15T06:14:18.708+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=21714) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-15T06:14:18.719+0000] {standard_task_runner.py:63} INFO - Started process 21736 to run task
[2024-11-15T06:14:18.705+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'YfinanceToSnowflake', 'dbt_test', 'manual__2024-11-15T05:56:05.666841+00:00', '--job-id', '393', '--raw', '--subdir', 'DAGS_FOLDER/Conn_Forcasting_DagFile.py', '--cfg-path', '/tmp/tmpe5sv6ql4']
[2024-11-15T06:14:18.723+0000] {standard_task_runner.py:91} INFO - Job 393: Subtask dbt_test
[2024-11-15T06:14:18.893+0000] {task_command.py:426} INFO - Running <TaskInstance: YfinanceToSnowflake.dbt_test manual__2024-11-15T05:56:05.666841+00:00 [running]> on host 5bbe89177473
[2024-11-15T06:14:20.817+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='YfinanceToSnowflake' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T05:56:05.666841+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T05:56:05.666841+00:00'
[2024-11-15T06:14:20.834+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-15T06:14:20.838+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-15T06:14:20.840+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/stocks_mau && dbt test --profiles-dir /opt/***/stocks_mau']
[2024-11-15T06:14:20.890+0000] {subprocess.py:86} INFO - Output:
[2024-11-15T06:14:33.908+0000] {subprocess.py:93} INFO - [0m06:14:33  Running with dbt=1.8.7
[2024-11-15T06:14:39.462+0000] {subprocess.py:93} INFO - [0m06:14:39  Registered adapter: snowflake=1.8.4
[2024-11-15T06:14:44.444+0000] {subprocess.py:93} INFO - [0m06:14:44  Found 2 snapshots, 2 models, 6 data tests, 1 source, 459 macros
[2024-11-15T06:14:44.455+0000] {subprocess.py:93} INFO - [0m06:14:44
[2024-11-15T06:14:45.948+0000] {subprocess.py:93} INFO - [0m06:14:45  Concurrency: 1 threads (target='dev')
[2024-11-15T06:14:46.086+0000] {subprocess.py:93} INFO - [0m06:14:46
[2024-11-15T06:14:46.282+0000] {subprocess.py:93} INFO - [0m06:14:46  1 of 6 START test not_null_moving_average_date ................................. [RUN]
[2024-11-15T06:14:48.820+0000] {subprocess.py:93} INFO - [0m06:14:48  1 of 6 PASS not_null_moving_average_date ....................................... [[32mPASS[0m in 2.52s]
[2024-11-15T06:14:48.984+0000] {subprocess.py:93} INFO - [0m06:14:48  2 of 6 START test not_null_moving_average_symbol ............................... [RUN]
[2024-11-15T06:14:50.769+0000] {subprocess.py:93} INFO - [0m06:14:50  2 of 6 PASS not_null_moving_average_symbol ..................................... [[32mPASS[0m in 1.80s]
[2024-11-15T06:14:50.816+0000] {subprocess.py:93} INFO - [0m06:14:50  3 of 6 START test not_null_rsi_date ............................................ [RUN]
[2024-11-15T06:14:52.641+0000] {subprocess.py:93} INFO - [0m06:14:52  3 of 6 PASS not_null_rsi_date .................................................. [[32mPASS[0m in 1.81s]
[2024-11-15T06:14:52.668+0000] {subprocess.py:93} INFO - [0m06:14:52  4 of 6 START test not_null_rsi_symbol .......................................... [RUN]
[2024-11-15T06:14:53.746+0000] {subprocess.py:93} INFO - [0m06:14:53  4 of 6 PASS not_null_rsi_symbol ................................................ [[32mPASS[0m in 1.08s]
[2024-11-15T06:14:53.776+0000] {subprocess.py:93} INFO - [0m06:14:53  5 of 6 START test unique_moving_average_date__symbol ........................... [RUN]
[2024-11-15T06:14:53.824+0000] {subprocess.py:93} INFO - [0m06:14:53  5 of 6 ERROR unique_moving_average_date__symbol ................................ [[31mERROR[0m in 0.04s]
[2024-11-15T06:14:53.837+0000] {subprocess.py:93} INFO - [0m06:14:53  6 of 6 START test unique_rsi_date__symbol ...................................... [RUN]
[2024-11-15T06:14:53.891+0000] {subprocess.py:93} INFO - [0m06:14:53  6 of 6 ERROR unique_rsi_date__symbol ........................................... [[31mERROR[0m in 0.04s]
[2024-11-15T06:14:53.927+0000] {subprocess.py:93} INFO - [0m06:14:53
[2024-11-15T06:14:53.932+0000] {subprocess.py:93} INFO - [0m06:14:53  Finished running 6 data tests in 0 hours 0 minutes and 9.47 seconds (9.47s).
[2024-11-15T06:14:54.283+0000] {subprocess.py:93} INFO - [0m06:14:54
[2024-11-15T06:14:54.286+0000] {subprocess.py:93} INFO - [0m06:14:54  [31mCompleted with 2 errors and 0 warnings:[0m
[2024-11-15T06:14:54.289+0000] {subprocess.py:93} INFO - [0m06:14:54
[2024-11-15T06:14:54.315+0000] {subprocess.py:93} INFO - [0m06:14:54    Compilation Error in test unique_moving_average_date__symbol (models/input/schema.yml)
[2024-11-15T06:14:54.317+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__test_unique' takes no keyword argument 'columns'
[2024-11-15T06:14:54.318+0000] {subprocess.py:93} INFO - [0m06:14:54
[2024-11-15T06:14:54.321+0000] {subprocess.py:93} INFO - [0m06:14:54    Compilation Error in test unique_rsi_date__symbol (models/input/schema.yml)
[2024-11-15T06:14:54.323+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__test_unique' takes no keyword argument 'columns'
[2024-11-15T06:14:54.325+0000] {subprocess.py:93} INFO - [0m06:14:54
[2024-11-15T06:14:54.329+0000] {subprocess.py:93} INFO - [0m06:14:54  Done. PASS=4 WARN=0 ERROR=2 SKIP=0 TOTAL=6
[2024-11-15T06:14:56.383+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-15T06:14:56.388+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-15T06:14:56.458+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-15T06:14:56.504+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=YfinanceToSnowflake, task_id=dbt_test, run_id=manual__2024-11-15T05:56:05.666841+00:00, execution_date=20241115T055605, start_date=20241115T061418, end_date=20241115T061456
[2024-11-15T06:14:56.573+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 393 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 21736)
[2024-11-15T06:14:56.645+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-15T06:14:56.708+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T06:14:56.717+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
