[2024-10-24T19:54:44.335+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-24T19:54:44.525+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Assignment8_ELT_DAG.combineTables scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-24T19:54:44.555+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Assignment8_ELT_DAG.combineTables scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-24T19:54:44.556+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-24T19:54:44.581+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): combineTables> on 2024-10-23 00:00:00+00:00
[2024-10-24T19:54:44.594+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Assignment8_ELT_DAG', 'combineTables', 'scheduled__2024-10-23T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/Assignment8_ELT_DAG.py', '--cfg-path', '/tmp/tmpj7htaxmx']
[2024-10-24T19:54:44.600+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask combineTables
[2024-10-24T19:54:44.603+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2765) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-24T19:54:44.606+0000] {standard_task_runner.py:63} INFO - Started process 2768 to run task
[2024-10-24T19:54:44.711+0000] {task_command.py:426} INFO - Running <TaskInstance: Assignment8_ELT_DAG.combineTables scheduled__2024-10-23T00:00:00+00:00 [running]> on host d99256b0cb87
[2024-10-24T19:54:45.222+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Assignment8_ELT_DAG' AIRFLOW_CTX_TASK_ID='combineTables' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T00:00:00+00:00'
[2024-10-24T19:54:45.227+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-24T19:54:45.235+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.4-linuxkit-x86_64-with-glibc2.36
[2024-10-24T19:54:45.243+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-10-24T19:54:46.332+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-24T19:54:46.352+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Assignment8_ELT_DAG.py", line 42, in combineTables
    cur.execute(create_blob_query)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01b7e92a-0004-0cca-0001-8d570005e476: SQL compilation error:
Schema 'DEV.ANALYTICS' does not exist or not authorized.
[2024-10-24T19:54:46.446+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Assignment8_ELT_DAG, task_id=combineTables, run_id=scheduled__2024-10-23T00:00:00+00:00, execution_date=20241023T000000, start_date=20241024T195444, end_date=20241024T195446
[2024-10-24T19:54:46.499+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 27 for task combineTables (002003 (02000): 01b7e92a-0004-0cca-0001-8d570005e476: SQL compilation error:
Schema 'DEV.ANALYTICS' does not exist or not authorized.; 2768)
[2024-10-24T19:54:46.538+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-24T19:54:46.587+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-24T19:54:46.591+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
